(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var c,e="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},f;if("function"==typeof Object.setPrototypeOf)f=Object.setPrototypeOf;else{var g;a:{var h={b:!0},k={};try{k.__proto__=h;g=k.b;break a}catch(a){}g=!1}f=g?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var l=f,n=function(a,b){a.prototype=e(b.prototype);a.prototype.constructor=a;if(l)l(a,b);else for(var d in b)if("prototype"!=d)if(Object.defineProperties){var m=Object.getOwnPropertyDescriptor(b,d);m&&Object.defineProperty(a,d,m)}else a[d]=b[d]};var p=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},q=function(a){if(p(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&p(a))return a;return null};var r=function(){var a=HTMLElement.call(this)||this;a.a=null;a.frameWidth=0;a.frameHeight=0;return a};n(r,HTMLElement);c=r.prototype;c.connectedCallback=function(){if(!this.gwdIsLoaded()){var a=q(this);a?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad()}};
c.gwdLoad=function(){var a=this.parentElement.querySelector("canvas");a&&(this.a=a.getContext("2d"),this.frameWidth=parseInt(a.style.width,10),this.frameHeight=parseInt(a.style.height,10));var b=void 0===b?null:b;a=document.createEvent("CustomEvent");a.initCustomEvent("ready",!0,!0,b);this.dispatchEvent(a)};c.gwdIsLoaded=function(){return!!this.a};c.renderAnimation=function(){};
c.getSupportedSwipeDirection=function(){if("undefined"==typeof this.direction)return[0,0];switch(this.direction){case "lefttoright":return[1,0];case "righttoleft":return[-1,0];case "toptobottom":return[0,1];case "bottomtotop":return[0,-1];default:return[0,0]}};c.setDirection=function(){};c.resetDirection=function(){};var t=function(){return r.call(this)||this};n(t,r);t.prototype.renderAnimation=function(a,b,d){this.a.clearRect(0,0,this.frameWidth,this.frameHeight);this.a.save();this.a.globalCompositeOperation="lighter";this.a.globalAlpha=1-d;this.a.drawImage(a,0,0,this.frameWidth,this.frameHeight);this.a.globalAlpha=d;this.a.drawImage(b,0,0,this.frameWidth,this.frameHeight);this.a.restore()};customElements.define("gwd-fade",t);}).call(this);
