(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},k;if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var l;a:{var n={s:!0},p={};try{p.__proto__=n;l=p.s;break a}catch(a){}l=!1}k=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var q=k,r=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},t=r(this),goog=goog||{};var v=function(){this.o=""};v.prototype.toString=function(){return"SafeStyle{"+this.o+"}"};v.prototype.f=function(a){this.o=a};(new v).f("");var w=function(){this.m=""};w.prototype.toString=function(){return"SafeStyleSheet{"+this.m+"}"};w.prototype.f=function(a){this.m=a};(new w).f("");var x="currentIndex frameCount frameSnapInterval getFrame goToFrame goForwards goBackwards rotateOnce".split(" ");var y={w:"for",A:"highlight",B:"use-thumbnails"},z=[],A=0,B;for(B in y)z[A++]=y[B];var C=function(){var a=HTMLElement.call(this)||this;a.a=null;a.j=a.v.bind(a);a.i=a.u.bind(a);a.h=!1;a.b=null;a.c=[];a.g=!1;return a},D=HTMLElement;C.prototype=d(D.prototype);C.prototype.constructor=C;if(q)q(C,D);else for(var E in D)if("prototype"!=E)if(Object.defineProperties){var F=Object.getOwnPropertyDescriptor(D,E);F&&Object.defineProperty(C,E,F)}else C[E]=D[E];
C.prototype.connectedCallback=function(){if(!this.g){for(;this.firstChild;)this.removeChild(this.firstChild);this.b=this.ownerDocument.createElement("div");this.b.classList.add("button-container");this.appendChild(this.b);this.g=!0}this.b.addEventListener("click",this.l.bind(this),!0);G(this)};C.prototype.disconnectedCallback=function(){this.b.removeEventListener("click",this.l.bind(this));H(this)};C.prototype.attributeChangedCallback=function(a){if(this.g)switch(a){case "for":G(this);break;default:I(this)}};
var G=function(a){H(a);var b=a.getAttribute("for"),c=null,f=!1;if(b){c=document.getElementById(b);for(var g=!1,e=a.parentElement;!c&&e&&!g;e=e.parentElement)if((g="body"==e.tagName.toLowerCase())||e.hasAttribute("data-gwd-group"))c=e.querySelector('[data-gwd-grp-id="'+b+'"]');if(c)a:if(c){for(b=0;b<x.length;b++)if(!(x[b]in c)){f=!1;break a}f=!0}else f=!1}f&&(a.a=c,c.addEventListener("frameactivated",a.i),c.gwdIsLoaded()?I(a):c.addEventListener("ready",a.j))},H=function(a){a.a&&(a.a.removeEventListener("ready",
a.j),a.a.removeEventListener("frameactivated",a.i))};C.prototype.v=function(a){a.target==this.a&&I(this)};C.prototype.u=function(a){a.target==this.a&&J(this,a.detail.id)};C.prototype.l=function(a){for(a=a.target;a&&a!=this;a=a.parentElement)if(a.gwdTargetFrameNum){this.a.goToFrame(a.gwdTargetFrameNum);break}};
var I=function(a){var b=a.getAttribute("highlight");a.style.color=b||"";a.h=a.hasAttribute("use-thumbnails");for(a.c=[];a.b.firstChild;)a.b.removeChild(a.b.firstChild);if(a.a){b=a.a.frameSnapInterval||1;for(var c=a.h?b:1,f=0;f<a.a.frameCount;f+=b){var g=document.createElement("span");g.classList.add("button");for(var e=0;e<c;e++){var h=a.a.getFrame(f+e+1);if(!h)break;var u=void 0,m=document.createElement("span");a.h?(m.classList.add("frame-thumbnail"),(h="gwd-image"==h.tagName.toLowerCase()||"img"==
h.tagName.toLowerCase()?h:h.querySelector("gwd-image"))&&(u=h.getAttribute("source")||h.getAttribute("src")),m.style.backgroundImage=u?"url("+JSON.stringify(u)+")":"url(data:image/gif;base64,R0lGODlhAQABAPAAAGZmZgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==)"):m.classList.add("frame-dot");g.appendChild(m)}g.gwdTargetFrameNum=f+1;a.c.push(g);a.b.appendChild(g)}J(a)}},J=function(a,b){b=void 0!=b?b-1:a.a.currentIndex-1;a.a.frameSnapInterval&&(b=Math.floor(b/a.a.frameSnapInterval));for(var c=0;c<a.c.length;c++)a.c[c].classList.remove("active");
(a=a.c[b])&&a.classList.add("active")};t.Object.defineProperties(C,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return z}}});customElements.define("gwd-gallerynavigation",C);}).call(this);
